config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :collections, only: [:create, :show]
end

app/models/collection.rb
# == Schema Information
#
# Table name: collections
#
#  id         :integer          not null, primary key
#  hashtag    :string
#  start_date :datetime
#  end_date   :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  next_url   :string
#

class Collection < ActiveRecord::Base
  validates :hashtag, :start_date, :end_date, presence: true
  validates :hashtag, uniqueness: { scope: [:start_date, :end_date] }
  validate :end_date_gte_start_date

  has_many :instagram_contents

  before_save :normalize_dates

  def start_date_unix
    start_date.to_datetime.to_i
  end

  def end_date_unix
    end_date.to_datetime.to_i
  end

  private

  def normalize_dates
    self.start_date = self.start_date.beginning_of_day
    self.end_date = end_date.end_of_day
  end

  def end_date_gte_start_date
    errors.add(:end_date_gte_start_date, I18n.t('start_date_greater_than_end_date')) if end_date < start_date
  end
end

app/models/instagram_content.rb
# == Schema Information
#
# Table name: instagram_contents
#
#  id            :integer          not null, primary key
#  created_time  :datetime
#  caption_text  :text
#  media_url     :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  collection_id :integer
#  media_type    :string
#  username      :string
#  insta_link    :string
#

class InstagramContent < ActiveRecord::Base
  paginates_per 20

  validates :created_time, :caption_text, :media_url, :media_type, :username, :insta_link, presence: true
  validates :caption_text, uniqueness: { scope: [:created_time, :media_url, :media_type, :username, :insta_link] }
  validates :media_type, inclusion: { in: ['image', 'video'] }

  belongs_to :collection

  def is_image?
    media_type == 'image'
  end

  def is_video?
    media_type == 'video'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def show
    if params[:id]
      id = params[:id].to_i
      @collection = Collection.find_by_id(id)

      if params[:new_data] == 'true'
        InstagramService.new.get_next_recent_tagged_media(@collection)
      elsif @collection.instagram_contents.blank?
        InstagramService.new.get_recent_tagged_media(@collection) 
      end
      
      @instagram_contents = Collection.find_by_id(id).instagram_contents.order('id asc').page params[:page]

      if params[:new_data] == 'true'
        last_page = @instagram_contents.num_pages
        @instagram_contents = Collection.find_by_id(id).instagram_contents.order('id asc').page last_page
        params[:new_data] = 'false'
      end

      respond_to do |format|
        format.js
      end
    end
  end

  def create
    @collection = Collection.create(collections_params)

    respond_to do |format|
      format.js
    end
  end

  private

  def collections_params
    params.require(:collection).permit(
      :end_date,
      :hashtag,
      :start_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @collection = Collection.new
    @collections = Collection.all.order('id desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/collections/_collection.html.haml
.collection.well.well-sm{id: dom_id(collection)}
  %h4= collection.hashtag
  %strong
    = t('from')
    = collection.start_date.strftime("%d %b %Y")
    = t('to').downcase
    = collection.end_date.strftime("%d %b %Y")
  
  .pull-right
    = link_to t('view_collection_link_label'), collection_path(collection), remote: true, class: 'btn btn-lg btn-success'

  .clearfix

  .pagination

  .pull-right
    = link_to t('next_page_button_label'), collection_path(collection, new_data: true), remote: true, class: 'btn btn btn-primary'

  .media-gallery

app/views/collections/_new.html.haml
= form_for @collection, remote: true, html: {class: 'form-inline'} do |f|
  .alert.alert-danger.hidden
  .form-group
    = f.text_field :hashtag, class: 'form-control', placeholder: t('placeholder_hashtag_collection')
  .form-group
    = render 'shared/datepicker_input', name: 'start_date', f: f, placeholder: t('placeholder_start_date_collection')
  .form-group
    = render 'shared/datepicker_input', name: 'end_date', f: f, placeholder: t('placeholder_end_date_collection')
  .form-group
    = f.submit t('submit_tag_collection'), class: 'btn btn-primary'

app/views/collections/create.js.erb
if (<%= @collection.errors.count > 0 %>) {
  $("#new_collection .alert.alert-danger").html('').removeClass('hidden');
  <% @collection.errors.full_messages.each do |message| %>
    $("#new_collection .alert.alert-danger").append("<%= message %>");
  <% end %>
} else {
  $("#new_collection .alert.alert-danger").html('').addClass('hidden');
  $("#collections-list").prepend("<%= escape_javascript(render(@collection)) %>");
  $("#new_collection input[type=text]").val('');
}

app/views/collections/show.js.erb
$('#collection_<%= @collection.id %> .media-gallery').html("<%= escape_javascript(render partial: 'instagram_contents/instagram_content', collection: @instagram_contents) %>");
$('#collection_<%= @collection.id %> .media-gallery').append("<div class='clearfix'></div>");
$('#collection_<%= @collection.id %> .pagination').html("<%= escape_javascript(paginate(@instagram_contents, remote: true)) %>")

app/views/instagram_contents/_instagram_content.html.haml
.instagram_content.pull-left{id: dom_id(instagram_content)}
  = link_to instagram_content.insta_link, target: '_blank' do
    %p.media
      - if instagram_content.is_image?
        = image_tag instagram_content.media_url
      - elsif instagram_content.is_video?
        %video{width: '200', height: '240', controls: true}
          %source{src: instagram_content.media_url, type: 'video/mp4'}
          = t('browser_doesnt_support_video')
  %p.created_time
    = instagram_content.created_time
  %p.user
    %strong
      = "by #{instagram_content.username}"
  %p.caption_text
    = instagram_content.caption_text

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstagramBrowser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.haml
%h1
  = image_tag 'logo.jpg', size: '45'
  = t('home_title')

= render 'collections/new'

#collections-list
  = render @collections

app/views/shared/_datepicker_input.haml
= f.text_field name, value: '', placeholder: placeholder, "data-provide": "datepicker", class: 'form-control', "data-date-week-start": 1, "data-date-start-view": 2, "data-date-today-btn": "linked", "data-date-calendar-weeks": true, "data-date-today-highlight": true, "data-date-format": "yyyy-mm-dd", "data-date-autoclose": true